version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: proethica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASS
      POSTGRES_DB: ai_ethical_dm
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql:ro

  mcp:
    build:
      context: .
      dockerfile: docker/mcp.Dockerfile
    environment:
      MCP_SERVER_PORT: 5001
      MCP_HOST: 0.0.0.0
    expose:
      - "5001"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    environment:
      ENVIRONMENT: production
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:PASS@db:5432/ai_ethical_dm
      MCP_SERVER_URL: http://mcp:5001
      USE_DB_VECTOR_SEARCH: "true"
      # Optionally set provider keys via .env
    env_file:
      - .env
    depends_on:
      - db
      - mcp
    ports:
  - "${HOST_HTTP_PORT:-8080}:8000"
    restart: unless-stopped

volumes:
  pgdata:
