version: '3'
services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: proethica-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PASS
      - POSTGRES_DB=ai_ethical_dm
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql:ro
volumes:
  pgdata:
