# Digital Ocean App Platform Spec
name: proethica-mcp-server
region: nyc
services:
  - name: mcp-server
    environment_slug: python
    github:
      repo: your-github-username/ai-ethical-dm
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements-mcp.txt
    run_command: python mcp/run_enhanced_mcp_server_with_guidelines.py
    http_port: 5001
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: MCP_SERVER_PORT
        scope: RUN_TIME
        value: "5001"
      - key: USE_MOCK_GUIDELINE_RESPONSES
        scope: RUN_TIME
        value: "false"
    routes:
      - path: /
databases:
  - name: proethica-db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1