"""
Configuration package for the application.
This package contains different configuration classes for different environments.
"""

class DevelopmentConfig:
    """Base configuration for development environment."""
    from app.config import (
        DEBUG, TESTING, SECRET_KEY, DATABASE_URL, SQLALCHEMY_DATABASE_URI,
        SQLALCHEMY_TRACK_MODIFICATIONS, SESSION_TYPE, SESSION_PERMANENT, SESSION_USE_SIGNER,
        WTF_CSRF_ENABLED, SET_CSRF_TOKEN_ON_PAGE_LOAD, UPLOAD_FOLDER, MAX_CONTENT_LENGTH,
        ENVIRONMENT, USE_AGENT_ORCHESTRATOR, USE_CLAUDE, OPENAI_API_KEY, ANTHROPIC_API_KEY,
        CLAUDE_MODEL_VERSION, EMBEDDING_PROVIDER_PRIORITY, LOCAL_EMBEDDING_MODEL,
        CLAUDE_EMBEDDING_MODEL, OPENAI_EMBEDDING_MODEL, ZOTERO_API_KEY,
        ZOTERO_USER_ID, ZOTERO_GROUP_ID, MCP_SERVER_URL, USE_MOCK_FALLBACK
    )

class CodespaceConfig:
    """Configuration for GitHub Codespaces environment."""
    from app.config.codespace import (
        DEBUG, TESTING, SECRET_KEY, DATABASE_URL, SQLALCHEMY_DATABASE_URI,
        SQLALCHEMY_TRACK_MODIFICATIONS, SESSION_TYPE, SESSION_PERMANENT, SESSION_USE_SIGNER,
        WTF_CSRF_ENABLED, SET_CSRF_TOKEN_ON_PAGE_LOAD, UPLOAD_FOLDER, MAX_CONTENT_LENGTH,
        ENVIRONMENT, USE_AGENT_ORCHESTRATOR, USE_CLAUDE, OPENAI_API_KEY, ANTHROPIC_API_KEY,
        CLAUDE_MODEL_VERSION, EMBEDDING_PROVIDER_PRIORITY, LOCAL_EMBEDDING_MODEL,
        CLAUDE_EMBEDDING_MODEL, OPENAI_EMBEDDING_MODEL, ZOTERO_API_KEY,
        ZOTERO_USER_ID, ZOTERO_GROUP_ID, MCP_SERVER_URL, USE_MOCK_FALLBACK,
        CODESPACE, ENABLE_LIVERELOAD, DB_SSL_MODE
    )

class ProductionConfig:
    """Configuration for production environment."""
    from app.config import (
        DEBUG, TESTING, SECRET_KEY, DATABASE_URL, SQLALCHEMY_DATABASE_URI,
        SQLALCHEMY_TRACK_MODIFICATIONS, SESSION_TYPE, SESSION_PERMANENT, SESSION_USE_SIGNER,
        WTF_CSRF_ENABLED, SET_CSRF_TOKEN_ON_PAGE_LOAD, UPLOAD_FOLDER, MAX_CONTENT_LENGTH,
        ENVIRONMENT, USE_AGENT_ORCHESTRATOR, USE_CLAUDE, OPENAI_API_KEY, ANTHROPIC_API_KEY,
        CLAUDE_MODEL_VERSION, EMBEDDING_PROVIDER_PRIORITY, LOCAL_EMBEDDING_MODEL,
        CLAUDE_EMBEDDING_MODEL, OPENAI_EMBEDDING_MODEL, ZOTERO_API_KEY,
        ZOTERO_USER_ID, ZOTERO_GROUP_ID, MCP_SERVER_URL, USE_MOCK_FALLBACK
    )
    
    # Override settings for production
    DEBUG = False
    TESTING = False
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
