"""
Seed extraction prompt templates from the enhanced_prompts_*.py files.

This seeder extracts the core prompt templates and stores them in the database,
allowing them to be edited through the web UI.
"""

import logging
from app.models import db
from app.models.extraction_prompt_template import (
    ExtractionPromptTemplate,
    PIPELINE_STEPS,
    CONCEPT_SOURCE_FILES
)

logger = logging.getLogger(__name__)


# Template definitions for each concept type
# These are extracted from the enhanced_prompts_*.py files and converted to Jinja2 syntax
INITIAL_TEMPLATES = {
    'roles': {
        'name': 'Roles Extraction',
        'description': 'Extract professional roles based on Kong et al. (2020) four-category framework',
        'step_number': 1,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology roles context', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL ROLES based on the ProEthica formalism and professional ethics literature.

THEORETICAL FRAMEWORK - Key Insights from Professional Ethics Literature:

Roles are not merely job titles but obligation-generating entities that:
- **Ethical Filters**: Transform general moral duties into role-specific obligations (Dennis et al. 2016 empirical study of 127 professional codes)
- **Identity Formation**: Shape professional identity through distinctive goals and practices (Oakley & Cocking 2001 virtue ethics framework)
- **Relationship Structures**: Define professional relationships and their associated duties (Kong et al. 2020 analysis of engineering ethics cases)

**KONG ET AL. (2020) FOUR-CATEGORY FRAMEWORK:**
Based on analysis of 500+ engineering ethics cases, all professional roles fall into these categories:

1. **Provider-Client** -> Service delivery relationships (Engineer-Client)
   - Duties: Competent service, confidentiality, client welfare

2. **Professional Peer** -> Collegial relationships (Senior-Junior, Mentor-Mentee)
   - Duties: Peer review, mentoring, knowledge sharing

3. **Employer Relationship** -> Organizational relationships (Employee-Employer)
   - Duties: Loyalty, competent performance, honest reporting

4. **Public Responsibility** -> Societal obligations (Engineer-Public)
   - Duties: Public welfare paramount, can override other interests

**EXTRACTION PROCESS:**
1. Identify all roles mentioned (explicit or implied)
2. Match against existing ontology roles (use is_existing: true/false)
3. Categorize using Kong framework (required for all roles)
4. Identify obligations generated by each role
5. Note role conflicts if present

GUIDELINE TEXT:
{{ text }}

**MATCH DECISION RULES:**
For each role, evaluate against the existing ontology roles listed above:
- If the extracted role IS the same concept as an existing class: match with HIGH confidence (0.85-1.0)
- If the extracted role is a SPECIALIZATION of an existing class: match to parent with MEDIUM confidence (0.70-0.85)
- If the extracted role is RELATED but distinct: do NOT match, it's a new concept
- If genuinely NEW with no close equivalent: match_decision.matches_existing = false

OUTPUT: JSON array with ALL roles found:
[
  {
    "label": "Environmental Engineer",
    "description": "Licensed engineer specializing in environmental impact assessment",
    "type": "role",
    "role_category": "provider_client",
    "obligations_generated": ["Environmental protection", "Accurate reporting", "Public safety"],
    "text_references": ["Engineer A, an environmental engineer"],
    "importance": "high",
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "http://proethica.org/ontology/intermediate#Engineer",
      "matched_label": "Engineer",
      "confidence": 0.85,
      "reasoning": "Environmental Engineer is a specialization of the existing Engineer class. Core professional obligations align."
    }
  }
]

If no match exists, use:
    "match_decision": {
      "matches_existing": false,
      "matched_uri": null,
      "matched_label": null,
      "confidence": 0.0,
      "reasoning": "This is a novel role type not represented in the current ontology."
    }

REMEMBER: Check ALL roles against the existing ontology roles listed above FIRST!'''
    },

    'states': {
        'name': 'States Extraction',
        'description': 'Extract professional states based on Event Calculus fluent framework',
        'step_number': 1,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology states context', 'optional': True},
            'roles_context': {'type': 'string', 'description': 'Previously extracted roles', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL STATES based on the ProEthica formalism and Event Calculus literature.

THEORETICAL FRAMEWORK - Key Insights:

States represent fluents - time-varying properties that:
- **Persist Until Changed**: States hold continuously until explicitly terminated by events (Berreby et al. 2017)
- **Enable/Disable Actions**: States determine what actions are possible or required (Rao et al. 2023)
- **Context for Obligations**: States activate or deactivate specific professional obligations (Almpani et al. 2023)

**STATE CATEGORIES:**

1. **Conflict States** - Competing interests or obligations
   - Examples: conflict_of_interest, dual_loyalty, role_conflict

2. **Risk States** - Safety or harm potential
   - Examples: public_safety_risk, environmental_hazard, professional_liability

3. **Competence States** - Knowledge or capability status
   - Examples: technically_qualified, licensed, informed_consent_obtained

4. **Relationship States** - Professional connections
   - Examples: client_relationship_active, supervisory_role, mentorship

5. **Information States** - Knowledge status
   - Examples: aware_of_defect, knowledge_of_violation, disclosure_made

6. **Emergency States** - Crisis conditions
   - Examples: immediate_danger, time_critical, resource_constrained

**EXTRACTION PROCESS:**
1. Identify states from the text (explicit and implied)
2. Classify persistence type (inertial vs momentary)
3. Link to affected roles from Pass 1
4. Identify triggering events and terminating conditions

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL states found:
[
  {
    "label": "Conflict of Interest",
    "description": "State where professional's personal interests may compromise professional judgment",
    "type": "state",
    "state_category": "conflict",
    "persistence": "inertial",
    "affects_roles": ["Engineer", "Supervisor"],
    "obligation_activation": ["Must disclose", "Must recuse"],
    "text_references": ["where personal interests..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "Conflict of Interest",
      "confidence": 0.9,
      "reasoning": "Direct match to existing state concept"
    }
  }
]'''
    },

    'resources': {
        'name': 'Resources Extraction',
        'description': 'Extract professional resources based on McLaren extensional principles approach',
        'step_number': 1,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology resources context', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL RESOURCES based on McLaren's extensional principles approach.

THEORETICAL FRAMEWORK:

Resources are ethical knowledge sources that:
- **Ground Abstract Principles**: Connect theoretical ethics to professional practice (McLaren 2003)
- **Provide Precedent**: Past decisions that guide current ethical reasoning
- **Establish Authority**: Sources that legitimize professional judgments

**RESOURCE TYPES:**

1. **Professional Codes** - Codified ethical standards
   - Examples: NSPE Code, IEEE Code, AMA Code
   - Authority: High (profession-wide consensus)

2. **Case Precedents** - Past ethical decisions
   - Examples: BER cases, Court decisions, Ethics board rulings
   - Authority: Medium-High (contextual application)

3. **Expert Interpretations** - Scholarly analysis
   - Examples: Ethics committee opinions, Academic literature
   - Authority: Medium (informed perspective)

4. **Technical Standards** - Professional practice guidelines
   - Examples: Building codes, Safety regulations, Best practices
   - Authority: High (technical consensus)

**EXTRACTION PROCESS:**
1. Identify all referenced resources in the text
2. Classify resource type and authority level
3. Note how the resource is used (normative vs advisory)
4. Extract specific provisions or sections cited

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL resources found:
[
  {
    "label": "NSPE Code of Ethics",
    "description": "National Society of Professional Engineers ethical guidelines",
    "type": "resource",
    "resource_type": "professional_code",
    "authority_level": "high",
    "specific_provisions": ["II.1.a", "III.2.b"],
    "usage_context": "normative",
    "text_references": ["As stated in the NSPE Code..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "NSPE Code",
      "confidence": 0.95,
      "reasoning": "Direct reference to established code"
    }
  }
]'''
    },

    'principles': {
        'name': 'Principles Extraction',
        'description': 'Extract ethical principles based on operationalization framework (Taddeo et al. 2024)',
        'step_number': 2,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology principles context', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract ETHICAL PRINCIPLES based on the ProEthica formalism.

THEORETICAL FRAMEWORK:

Principles are abstract ethical commitments that:
- **Guide Action**: Shape professional behavior across contexts (Anderson & Anderson 2018)
- **Generate Obligations**: Create specific duties when applied to situations
- **Require Operationalization**: Must be made concrete for practical application (Taddeo et al. 2024)

**PRINCIPLE CATEGORIES:**

1. **Fundamental Principles** - Core ethical commitments
   - Examples: Public safety paramount, Professional integrity, Competence

2. **Professional Virtue Principles** - Character-based standards
   - Examples: Honesty, Fairness, Fidelity, Care

3. **Relational Principles** - Duty-based standards
   - Examples: Confidentiality, Loyalty, Non-maleficence

4. **Domain-Specific Principles** - Field-specific standards
   - Examples: Environmental protection (environmental eng.), Patient autonomy (medical)

**OPERATIONALIZATION PROCESS (Taddeo et al. 2024):**
1. Identify abstract principle statement
2. Determine scope of application
3. Identify conditions for activation
4. Derive concrete obligations

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL principles found:
[
  {
    "label": "Public Safety Paramount",
    "description": "Engineers shall hold paramount the safety, health, and welfare of the public",
    "type": "principle",
    "principle_category": "fundamental",
    "scope": "All professional activities",
    "activation_conditions": ["Engineering decisions", "Technical recommendations"],
    "derived_obligations": ["Report safety concerns", "Refuse unsafe work"],
    "text_references": ["hold paramount the safety..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "Public Safety",
      "confidence": 0.92,
      "reasoning": "Core principle in engineering ethics ontology"
    }
  }
]'''
    },

    'obligations': {
        'name': 'Obligations Extraction',
        'description': 'Extract professional obligations based on deontic logic framework',
        'step_number': 2,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology obligations context', 'optional': True},
            'principles_context': {'type': 'string', 'description': 'Previously extracted principles', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL OBLIGATIONS based on deontic logic.

THEORETICAL FRAMEWORK:

Obligations are normative requirements that:
- **Bind Agents**: Create duties for specific role-holders (Dennis et al. 2016)
- **Derive from Principles**: Concrete expressions of abstract ethical commitments
- **Can Conflict**: Multiple obligations may compete in specific situations (Wooldridge & Jennings 1995)

**OBLIGATION CATEGORIES:**

1. **Fundamental Duties** - Core professional requirements
   - Examples: Competent practice, Safety protection, Honest reporting

2. **Professional Practice** - Standards of conduct
   - Examples: Continuing education, Proper supervision, Documentation

3. **Disclosure Obligations** - Information duties
   - Examples: Conflict disclosure, Risk communication, Error reporting

4. **Collegial Obligations** - Peer responsibilities
   - Examples: Peer support, Mentoring, Professional development

5. **Societal Obligations** - Public duties
   - Examples: Public welfare, Environmental protection, Safety advocacy

**EXTRACTION PROCESS:**
1. Identify explicit and implicit obligations
2. Determine obligation type and enforcement level
3. Link to source principle
4. Identify affected stakeholders
5. Note potential conflicts

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL obligations found:
[
  {
    "label": "Disclose Conflicts of Interest",
    "description": "Obligation to reveal situations where personal interests may affect professional judgment",
    "type": "obligation",
    "obligation_type": "disclosure",
    "enforcement_level": "mandatory",
    "derived_from_principle": "Professional Integrity",
    "stakeholders_affected": ["Client", "Employer", "Public"],
    "potential_conflicts": ["Confidentiality obligations"],
    "monitoring_criteria": "Disclosure made before engagement",
    "text_references": ["shall disclose..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "Conflict Disclosure",
      "confidence": 0.88,
      "reasoning": "Standard professional obligation in ethics codes"
    }
  }
]'''
    },

    'constraints': {
        'name': 'Constraints Extraction',
        'description': 'Extract professional constraints based on deontic prohibition framework',
        'step_number': 2,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology constraints context', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL CONSTRAINTS based on deontic logic.

THEORETICAL FRAMEWORK:

Constraints are prohibitions or limitations that:
- **Bound Action Space**: Define what professionals must NOT do (Ganascia 2007)
- **Complement Obligations**: While obligations require action, constraints forbid it
- **May Be Defeasible**: Some constraints can be overridden in exceptional circumstances (Dennis et al. 2016)

**CONSTRAINT TYPES:**

1. **Legal Constraints** - Law-based prohibitions
   - Examples: Anti-bribery, Antitrust, Licensing requirements

2. **Regulatory Constraints** - Agency-imposed limits
   - Examples: EPA regulations, OSHA requirements, Professional board rules

3. **Resource Constraints** - Practical limitations
   - Examples: Budget limits, Time constraints, Expertise boundaries

4. **Competence Constraints** - Knowledge/skill limits
   - Examples: Scope of practice, Certification requirements

5. **Confidentiality Constraints** - Information restrictions
   - Examples: Trade secrets, Client privacy, Proprietary data

**EXTRACTION PROCESS:**
1. Identify prohibitions and limitations
2. Classify constraint type
3. Assess defeasibility (can it be overridden?)
4. Identify conditions that activate the constraint

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL constraints found:
[
  {
    "label": "Confidentiality of Client Information",
    "description": "Prohibition on disclosing client proprietary information without consent",
    "type": "constraint",
    "constraint_type": "confidentiality",
    "defeasible": true,
    "override_conditions": ["Court order", "Public safety emergency"],
    "enforcement_mechanism": "Professional discipline, Legal action",
    "text_references": ["shall not disclose..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "Client Confidentiality",
      "confidence": 0.90,
      "reasoning": "Standard professional constraint"
    }
  }
]'''
    },

    'capabilities': {
        'name': 'Capabilities Extraction',
        'description': 'Extract professional capabilities based on competence framework',
        'step_number': 2,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology capabilities context', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL CAPABILITIES based on competence literature.

THEORETICAL FRAMEWORK:

Capabilities are competencies that:
- **Enable Obligation Fulfillment**: Required to perform professional duties (Tolmeijer et al. 2021)
- **Include Technical & Ethical Skills**: Both domain expertise and moral reasoning (Berreby et al. 2017)
- **Can Be Meta-Capabilities**: Ability to recognize limits of own capabilities (Anderson & Anderson 2018)

**CAPABILITY CATEGORIES:**

1. **Technical Capabilities** - Domain expertise
   - Examples: Design analysis, Risk assessment, Technical documentation

2. **Ethical Reasoning Capabilities** - Moral judgment skills
   - Examples: Conflict identification, Stakeholder analysis, Value balancing

3. **Communication Capabilities** - Information transfer skills
   - Examples: Technical writing, Risk communication, Public engagement

4. **Perceptual Capabilities** - Recognition skills
   - Examples: Hazard identification, Ethical issue recognition, Conflict detection

5. **Learning Capabilities** - Development skills
   - Examples: Continuing education, Skill updating, Knowledge transfer

**EXTRACTION PROCESS:**
1. Identify capabilities required or referenced
2. Classify capability type
3. Link to obligations that require this capability
4. Note any capability gaps or development needs

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL capabilities found:
[
  {
    "label": "Risk Assessment Capability",
    "description": "Ability to identify, evaluate, and communicate professional and public risks",
    "type": "capability",
    "capability_type": "technical",
    "required_for_obligations": ["Report safety concerns", "Advise on project risks"],
    "development_path": "Formal training, Supervised practice",
    "text_references": ["must be able to assess..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "Risk Assessment",
      "confidence": 0.85,
      "reasoning": "Core professional capability"
    }
  }
]'''
    },

    'actions': {
        'name': 'Actions Extraction',
        'description': 'Extract professional actions based on Event Calculus action framework',
        'step_number': 3,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology actions context', 'optional': True},
            'pass1_context': {'type': 'string', 'description': 'Pass 1 entities (roles, states, resources)', 'optional': True},
            'pass2_context': {'type': 'string', 'description': 'Pass 2 entities (principles, obligations, constraints, capabilities)', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL ACTIONS based on Event Calculus.

THEORETICAL FRAMEWORK:

Actions are volitional professional activities that:
- **Are Chosen by Agents**: Deliberate decisions by role-holders (Chapter 2.2.6)
- **Fulfill or Violate Obligations**: Connected to normative requirements
- **Change States**: Actions initiate or terminate states
- **Require Capabilities**: Need specific competencies to perform

**CRITICAL DISTINCTION:**
- **Actions** = Volitional choices BY agents (engineer decides to report)
- **Events** = Occurrences that happen (discovery is made, deadline passes)

**ACTION TYPES:**

1. **Communication Actions** - Information transfer
   - Examples: Report issue, Disclose conflict, Document decision

2. **Prevention Actions** - Harm avoidance
   - Examples: Stop work, Refuse assignment, Implement safeguard

3. **Evaluation Actions** - Assessment activities
   - Examples: Review design, Assess risk, Analyze options

4. **Collaboration Actions** - Joint activities
   - Examples: Consult expert, Seek review, Coordinate response

{{ pass1_context }}

{{ pass2_context }}

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL actions found:
[
  {
    "label": "Report Safety Concern",
    "description": "Action of formally communicating identified safety issues to appropriate parties",
    "type": "action",
    "action_type": "communication",
    "performed_by_roles": ["Engineer", "Supervisor"],
    "fulfills_obligations": ["Report safety concerns", "Protect public welfare"],
    "requires_capabilities": ["Risk Assessment", "Technical Communication"],
    "constrained_by": ["Confidentiality limits", "Chain of command"],
    "changes_states": ["Initiates: Disclosure made", "Terminates: Undisclosed hazard"],
    "text_references": ["engineer shall report..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "Safety Reporting",
      "confidence": 0.88,
      "reasoning": "Standard professional action"
    }
  }
]'''
    },

    'events': {
        'name': 'Events Extraction',
        'description': 'Extract professional events based on Event Calculus occurrence framework',
        'step_number': 3,
        'variables_schema': {
            'text': {'type': 'string', 'description': 'The guideline text to analyze'},
            'mcp_context': {'type': 'string', 'description': 'Existing ontology events context', 'optional': True},
            'pass1_context': {'type': 'string', 'description': 'Pass 1 entities (roles, states, resources)', 'optional': True},
            'pass2_context': {'type': 'string', 'description': 'Pass 2 entities (principles, obligations, constraints, capabilities)', 'optional': True}
        },
        'template_text': '''{{ mcp_context }}

You are analyzing an ethics guideline to extract PROFESSIONAL EVENTS based on Event Calculus.

THEORETICAL FRAMEWORK:

Events are occurrences that:
- **Happen At Points in Time**: Discrete temporal occurrences (Chapter 2.2.7)
- **Trigger Ethical Considerations**: Create situations requiring professional judgment
- **May Result from Actions or Be External**: Both agent-caused and environmental
- **Change State of Affairs**: Initiate or terminate states

**CRITICAL DISTINCTION:**
- **Events** = Occurrences (discovery happens, deadline arrives, failure occurs)
- **Actions** = Volitional choices BY agents (engineer decides, manager orders)

**EVENT TYPES:**

1. **Crisis Events** - Emergency occurrences
   - Examples: System failure, Safety incident, Environmental spill

2. **Compliance Events** - Regulatory occurrences
   - Examples: Audit finding, Violation discovery, License expiration

3. **Project Events** - Work milestones
   - Examples: Project completion, Phase transition, Deadline arrival

4. **Discovery Events** - Information revelation
   - Examples: Defect discovered, Risk identified, Conflict revealed

{{ pass1_context }}

{{ pass2_context }}

GUIDELINE TEXT:
{{ text }}

OUTPUT: JSON array with ALL events found:
[
  {
    "label": "Safety Defect Discovery",
    "description": "Event where a safety-critical defect is identified in a design or product",
    "type": "event",
    "event_type": "discovery",
    "is_external": false,
    "caused_by_actions": ["Design review", "Testing"],
    "triggers_obligations": ["Report to authorities", "Notify affected parties"],
    "changes_states": ["Initiates: Known defect state", "Activates: Disclosure duty"],
    "affects_roles": ["Design Engineer", "Quality Manager", "Project Manager"],
    "text_references": ["when a defect is discovered..."],
    "match_decision": {
      "matches_existing": true,
      "matched_uri": "...",
      "matched_label": "Defect Discovery",
      "confidence": 0.85,
      "reasoning": "Common event in safety-critical contexts"
    }
  }
]'''
    }
}


def seed_extraction_prompt_templates():
    """Seed initial extraction prompt templates from the enhanced_prompts_*.py files."""
    logger.info("Seeding extraction prompt templates...")

    created_count = 0
    updated_count = 0
    skipped_count = 0

    for concept_type, template_data in INITIAL_TEMPLATES.items():
        # Check if template already exists
        existing = ExtractionPromptTemplate.query.filter_by(
            step_number=template_data['step_number'],
            concept_type=concept_type,
            pass_type='all',
            is_active=True
        ).first()

        if existing:
            logger.info(f"Template for {concept_type} already exists (id={existing.id}), skipping")
            skipped_count += 1
            continue

        # Create new template
        template = ExtractionPromptTemplate(
            step_number=template_data['step_number'],
            concept_type=concept_type,
            pass_type='all',
            name=template_data['name'],
            description=template_data['description'],
            template_text=template_data['template_text'],
            variables_schema=template_data['variables_schema'],
            source_file=CONCEPT_SOURCE_FILES.get(concept_type),
            created_by='seeder',
            is_active=True,
            version=1
        )

        db.session.add(template)
        created_count += 1
        logger.info(f"Created template for {concept_type} (step {template_data['step_number']})")

    db.session.commit()

    logger.info(f"Seeding complete: {created_count} created, {updated_count} updated, {skipped_count} skipped")
    return created_count, updated_count, skipped_count


def run_seeder():
    """Run the seeder from the command line or Flask shell."""
    from flask import current_app
    with current_app.app_context():
        return seed_extraction_prompt_templates()


if __name__ == '__main__':
    # For running directly (requires Flask app context)
    import sys
    sys.path.insert(0, '/home/chris/onto/proethica')
    from app import create_app
    app = create_app()
    with app.app_context():
        seed_extraction_prompt_templates()
