"""Add domains table and update scenarios with domain_id

Revision ID: e99487662b4f
Revises: 1ba57eb97265
Create Date: 2025-03-16 18:36:31.362204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99487662b4f'
down_revision = '1ba57eb97265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Create default domains
    op.bulk_insert(
        sa.table('domains',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('description', sa.Text)
        ),
        [
            {'id': 1, 'name': 'Military Medical Triage', 'description': 'Ethical decision-making in military medical triage scenarios'},
            {'id': 2, 'name': 'Engineering Ethics', 'description': 'Ethical decision-making in engineering scenarios'},
            {'id': 3, 'name': 'US Law Practice', 'description': 'Ethical decision-making in US law practice scenarios'}
        ]
    )
    
    # Add domain_id column as nullable first
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'domains', ['domain_id'], ['id'])
    
    # Update existing scenarios to use the Military Medical Triage domain
    op.execute("UPDATE scenarios SET domain_id = 1")
    
    # Now make domain_id not nullable
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('domain_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('domain_id')

    op.drop_table('domains')
    # ### end Alembic commands ###
