name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to Digital Ocean
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd /home/chris/proethica && git clean -f backups/ai_ethical_dm_backup_20250323_135340.dump backups/restore_database.sh && git pull && source venv/bin/activate && pip install -r requirements.txt && (pkill -f "gunicorn" || true) && nohup gunicorn --workers 3 --bind 127.0.0.1:5001 "app:create_app('\''production'\'')" > /dev/null 2>&1 &'
